### ISSUE TITLE
[BUG] When chatting with Damien's smartphones sometimes the text juts out from the box

### ISSUE THREAD

**Issue by yrochat** [IMI-initiative/quatre-apparts-et-un-confinement#125]
It concerns boxes with 4 lines of text, but not all of them. I wondered if it was related to the use of emojis but it was not.

<img width="451" alt="Screenshot 2020-07-21 at 00 34 35" src="https://user-images.githubusercontent.com/3351331/87993241-5080d580-caea-11ea-8569-7e7be85c004e.png">

<img width="436" alt="Screenshot 2020-07-21 at 00 34 19" src="https://user-images.githubusercontent.com/3351331/87993249-54145c80-caea-11ea-8457-dc1889c19a8d.png">

**Comment by Dobios** [comment]
This is a problem I'm aware of, but not quite sure how to solve without changing the way I handle the choice of box sizes. For the time being, I'm handling the box choices by looking at the character count of a bit of text and using a `MAX_CHARS_PER_LINE` constant to decide when to skip to a next line. This is why using emojis might affect it since they are technically still a single character yet they take up quite a bit of space.  

I have 2 possible solutions:  

- [ ] ___QUICK & EASY___ Lower the `MAX_CHARS_PER_LINE` value in order to pick bigger boxes easier, this will work but will mean that we will probably often chose boxes that are too large for the amount of text we want to display.  

- [ ] ___SLOW BUT BETTER RESULT___ Instead of using the character count, use the text's height (better result probably but will demand a bit of work to get working correctly).

**Comment by yrochat** [comment]
You've implemented the quick & easy one, right? If that's the case I must say I'm not shocked by the bigger margins. I have problems for the tiny ones however :-)
