### ISSUE TITLE
Harmonize variable and method names

### ISSUE THREAD

**Issue by palrogg** [IMI-initiative/quatre-apparts-et-un-confinement#166]
- [x] protoScene.js & protoScene folder -> studentScene
- [x] damien*.js -> student*.js
- [ ] player.js properties / database columns: identical keys; nathan_failed / good_advice: make it non-judgmental
- [ ] Ask someone to have a look at our code and tell us what seems her/him the most obfuscate

Also why do we have mostly letter-case separation (methods, most variables) but sometimes underscores (current_card, parent_scene)? Very low priority for this.

@yrochat more thoughts about variable naming?

**Comment by yrochat** [comment]
Not much more thoughts. I think most of our variable names are neutral, which is important since we don't want to offer an _opinion_ on the action of the government neither do we want to criminalise some of people's actions. 

The only thing I see at this point is that there is a lot of French in the names of dialog boxes :-)

**Comment by palrogg** [comment]
You mean in the json files?

**Comment by yrochat** [comment]
Yes. In more or less all of them.

**Comment by Dobios** [comment]
What I try to do regarding the case is camelCase for the method names, PascalCase for type and class names and snake_case for the variable names. But I do have to admit that I sometimes used camelCase for variables... My bad

**Comment by Dobios** [comment]
If we were to pick one, I would say 100% camelCase to match Phaser's case

**Comment by palrogg** [comment]
Shrinking to minimum viable product -> closed
